### ISSUE TITLE
Songs with multiple artists giving wrong lyrics

### ISSUE THREAD

**Issue by Shanamaj** [fr31/spotifylyrics#14]
Many songs with multiple artists are showing lyrics from some other song or none at all, see examples below

**No lyrics:**
Aici cu mine by Proconsul, Stefan Banica, Andra

**Wrong lyrics:**
Salut! Ce Faci? by Directia 5, Nicoleta Nuca
Mai sus by Stela Botan, Paralela 47
Mama by F.Chart, Elena Gheorghe
Karma by Leya D, Kalif

**Comment by fr31** [comment]
The first three I think just aren't on any of the lyric sites the program fetches from. (at least I couldn't find them when I looked manually, let me know if you could find them though) So it may just be getting the best match it can find which would obviously be wrong.

The last two it seems to be finding the correct lyrics for me. It displays the lyrics from these pages:

https://www.musixmatch.com/lyrics/F-Charm-feat-Elena-Gheorghe/Mama
https://www.musixmatch.com/lyrics/Leya-D-feat-Kalif/Karma

(you can click on the song name to see where the lyrics are coming from)

So it seems the problem is actually the sites that the program fetches from just don't have the lyrics.

If you know of another site for fetching lyrics that would have these songs (and perhaps more), I could see about adding it though.

**Comment by Shanamaj** [comment]
Thanks for your quick response! The two you found also work for me now, hadn't noticed the 1.09 version release.

The others are available at versuri.ro, would be great to have that one included!

**Comment by fr31** [comment]
I added versuri as a provider in 1.10.

https://github.com/fr31/spotifylyrics/releases

**Comment by Shanamaj** [comment]
Awesome, thanks!

**Comment by Shanamaj** [comment]
Seems common for songs in another language than English to add English title as part of the song. Lyrics fetch fine in the songs I've seen this when the English title is encapsulated in parentheses but when separated by a front slash "/" it does not. The song Voltaj - Povestea oricui / Anybody's story does not give lyrics from below link.

http://www.versuri.ro/versuri/jeig_voltaj-povestea-oricui.html

Small detail and maybe uncommon in general though.

**Comment by fr31** [comment]
I'll see what I can do about that this weekend.

**Comment by fr31** [comment]
@Shanamaj the issue should be fixed in the latest release.

**Comment by Shanamaj** [comment]
Works perfectly, thanks!
