### ISSUE TITLE
Lyric Syncing isn't entirely Spot on

### ISSUE THREAD

**Issue by muujagal** [fr31/spotifylyrics#18]
Sometimes the Lyrics are a few lines ahead or behind. It's random every time, is there a way to fix this?

**Comment by archagy** [comment]
Well I think it's because of the source of the lyrics. But will be interesting implement a tempo tool and reduce or add more time

**Comment by fr31** [comment]
Yeah, the lyrics on minilyrics (where the program fetches from) are user submitted so they may not always be perfectly in sync due to either bad syncing on the users part or they may just have synced it to a different version of the song. If it's just off by a little bit, you can manually seek forwards or backwards a bit in spotify and it will fix it.
