### ISSUE TITLE
[Improvement] App is not grabbing new Song, if searching lyrics from other song.

### ISSUE THREAD

**Issue by AndiKnight** [fr31/spotifylyrics#21]
Hi there,

not really an issue but yeah I wanted to say it. So it's probably more an FYI ;) 
If a lyrics need really long to load, and while its loading you switch the Song you'll have to wait until its finished loading before the new song lyrics get fetched. 

![gif](http://i.imgur.com/yxPbLB9.gif)

Also it's causing that the "new" song lyrics will be out of sync.

(And yeah, the lyrics for this song is pretty wrong: https://open.spotify.com/track/6b5rA9rthDbZDOQp9UbOgl )

**Comment by archagy** [comment]
Yeah, I noticed too the same issue. But it is because the program get the info(title) window and has some delay on the loop.

And with the lyrics what is the source where are you getting the lyrics?

For example when I play the song this is the link I get:

http://minilyrics.com/lu4/9d/fq_spwoqosh.lrc

**Comment by fr31** [comment]
I didn't fix this issue per se, but I think I fixed a slow down issue that made this issue happen more often than it normally would. So it should happen less in the newest version.
