### ISSUE TITLE
Synced Lyrics do not go to start when starting song from start

### ISSUE THREAD

**Issue by nick-2017** [fr31/spotifylyrics#40]
When I'm listening to a song with synced lyrics on, halfway through I press the button in spotify that looks like  |< (back button) which starts the song from the start but the synced lyrics do not reset.

**Comment by nick-2017** [comment]
Screen recording of the issue: https://files.simpleshare.pw/nick/images/YAC.mp4
There is no sound, I tried to follow the lyrics in the song with my mouse.

**Comment by fr31** [comment]
Sorry, this can't be fixed without an api or something. (as far as I'm aware)

The program looks for changes in the window title to know when to start highlighting the synced lyrics.

No song --> "Spotify"
Song --> "Song Name - Song Artist" - starts showing synced lyrics
Pause --> "Spotify" - pauses synced lyrics
Song --> Song Name - Song Artist" - resumes synced lyrics if it's the same song otherwise loads new lyrics

Seeking doesn't change the window title at all unfortunately.
