### ISSUE TITLE
Synced lyrics

### ISSUE THREAD

**Issue by mirh** [fr31/spotifylyrics#55]
https://github.com/spotify/web-api/issues/12#issuecomment-290726036 !

I'm not sure how [this](https://github.com/fr31/spotifylyrics/issues/2#issuecomment-233379198) was ever supposed to work then.

**Comment by mrkiller2010** [comment]
The current synced lyrics is really bad, anyway to fix this? Use another api?

**Comment by Arecsu** [comment]
Complicated. To work properly, it will need a memory hook to know the current timer of the song, which is kind of huge. Or re-write the application entirely to get the timer from the spotify api. But it will need log in from user, API authentication, etc. 

Basically, a new application. It will be fun to make something from scratch, like a html-based application, with a GUI similar to the musixmatch lyrics that spotify had time ago.

Speaking for this current implementation, seems like almost impossible. Unless someone with knowledge of memory access, reading and python/c gets over this.

**Comment by mirh** [comment]
The memory hook would certainly be golden.. But I'm not sure which part of "getting current timestamp through web api" entails rewriting the application.

**Comment by xDebuggerx** [comment]
Sometimes it can be a hit and miss. Is there any way you could display for the user some sort of visual View as to what 'Change Lyrics' is changing (i.e. display the lyric source)? Otherwise it just seems very arbitrary.

Does the sync only work with certain lyric sources? i.e. if you find one source that works well alongside the sync, should you leave it as that?
